"""add image_path and plant_condition to tasks

Revision ID: ea55724616d2
Revises: c7f09bcaa0fc
Create Date: 2025-12-05 17:19:16.290428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea55724616d2'
down_revision: Union[str, Sequence[str], None] = 'c7f09bcaa0fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('image_path', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('plant_condition', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'plant_condition')
    op.drop_column('tasks', 'image_path')
    # ### end Alembic commands ###
